### ISSUE TITLE
docs: links to command help in appendix

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#8] opened 2019-04-07 20:08 UTC
Depends on #2972 

See discussion in #3037

**Comment by oliver-sanders** [comment] 2022-02-07 15:52
Duplicate of #124 

This is about doing this:

```rst
Hold tasks with :command:`cylc hold`.
```

Rather than this:

```rst
Hold tasks with ``cylc hold``.
```

The former creates a hyperlink to the relevant bit of the docs (blocked by #185) as well as providing a little integrity checking.

**Closed by oliver-sanders** 2022-02-07 15:52 UTC
Labels: content
