### ISSUE TITLE
doc build and dependencies

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#20] opened 2019-06-13 01:30 UTC
#3 moved all docs here from the cylc-flow repository, simplistically taking the relevant bits of `setup.py` and `cylc-check-software` with it.

We need to decide how best to build the docs here, and how best to depend (where necessary) on other project/repo versions, particularly cylc-flow.  (e.g. should we use `setup.py` here at all?)

See also #17

**Comment by kinow** [comment] 2019-06-19 11:24
Related to this one, we have an issue in `setup.py` that prevents the project from building in a new virtual environment. We have `sphinx` in `install_requires`. And we also do `import sphinx` in `setup.py`. The problem is that the import in `setup.py` is evaluated first, resulting in an `ImportError`.

Using `setup_requires` could solve it, if that was evaluated by pip. We could alternatively hack `setup.py` and install sphinx if not present. But I think that depends first on the decision pending in this issue.

**Comment by oliver-sanders** [comment] 2019-07-23 13:15
closed by #26

**Closed by oliver-sanders** 2019-07-23 13:15 UTC
